export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';

export const RECIPE_LIST_MRATE_REQUEST = 'RECIPE_LIST_MRATE_REQUEST';
export const RECIPE_LIST_MRATE_SUCCESS = 'RECIPE_LIST_MRATE_SUCCESS';
export const RECIPE_LIST_MRATE_FAIL = 'RECIPE_LIST_MRATE_FAIL';

export const RECIPE_LIST_ALL_REQUEST = 'RECIPE_LIST_ALL_REQUEST';
export const RECIPE_LIST_ALL_SUCCESS = 'RECIPE_LIST_ALL_SUCCESS';
export const RECIPE_LIST_ALL_FAIL = 'RECIPE_LIST_ALL_FAIL';

export const RECIPE_DETAIL_REQUEST = 'RECIPE_DETAIL_REQUEST';
export const RECIPE_DETAIL_SUCCESS = 'RECIPE_DETAIL_SUCCESS';
export const RECIPE_DETAIL_FAIL = 'RECIPE_DETAIL_FAIL';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';

export const RECIPE_UPDATE_REQUEST = 'RECIPE_UPDATE_REQUEST';
export const RECIPE_UPDATE_SUCCESS = 'RECIPE_UPDATE_SUCCESS';
export const RECIPE_UPDATE_FAIL = 'RECIPE_UPDATE_FAIL';

export const RECIPE_ADD_REQUEST = 'RECIPE_ADD_REQUEST';
export const RECIPE_ADD_SUCCESS = 'RECIPE_ADD_SUCCESS';
export const RECIPE_ADD_FAIL = 'RECIPE_ADD_FAIL';

export const RECIPE_REVIEWS_ADD_REQUEST = 'RECIPE_REVIEWS_ADD_REQUEST';
export const RECIPE_REVIEWS_ADD_SUCCESS = 'RECIPE_REVIEWS_ADD_SUCCESS';
export const RECIPE_REVIEWS_ADD_FAIL = 'RECIPE_REVIEWS_ADD_FAIL';
export const RECIPE_REVIEWS_ADD_RESET = 'RECIPE_REVIEWS_ADD_RESET';

export const CATEGORY_ADD_REQUEST = 'CATEGORY_ADD_REQUEST';
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
export const CATEGORY_ADD_FAIL = 'CATEGORY_ADD_FAIL';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';
